#! /bin/bash
# Then crontab -e
# Then add this line :
# 0 0 * * * path/to/script.sh

if [ ! -f $HOME/crontab.md5  ]
then
	md5sum /etc/crontab > $HOME/crontab.md5
elif ! md5sum -c $HOME/crontab.md5
then
	echo "/etc/crontab changed" | mail -s "/etc/crontab changed" root
	md5sum /etc/crontab > $HOME/crontab.md5
fi
